#ifndef ADD_CONSTH
#define ADD_CONSTH

#define NUMBER_OF_POINTS 16
#define NUMBER_OF_POINTS_2  (NUMBER_OF_POINTS * NUMBER_OF_POINTS)
#define NUMBER_OF_CLUSTERS 4
#define LENGTH_OF_CLUSTERS 2
#define WIDTH_OF_CLUSTERS 2


#endif